### ISSUE TITLE
Uniquely different from Element Map?

### ISSUE THREAD

**Issue by johndwells** [wrav/related#1]
Hey Regan,

Congrats on the plugin release. I was just wondering how different this plugin is from Element Map: https://plugins.craftcms.com/element-map

I can see that the way you present the relationships is different... but beyond that? Do you have a roadmap that would take it down a different path?

If not, perhaps you'd consider being a contributor to EM instead (I'm not the maintainer there but who would turn down help?!). I think the community is better served when there are less + higher quality plugins.

Cheers,
John

**Comment by reganlawton** [comment]
@johndwells We've discussed my plugin on Discord  but I'll summaries the discussion here.

The plugin meet a need for relationship visibility for large sites with large relationship lists. I'll be adding features such as search and filtering as well as other support for different content types and possibly quick editing. All to provide a slick content editing experience.
