### ISSUE TITLE
Possible issue with action path url in Related.js

### ISSUE THREAD

**Issue by gavinplatt** [wrav/related#14]
Thank you for this plugin, it's a massive help for our editors.

I'm hitting an issue using this plugin on a site which uses HTTPS. Works fine on local and staging which are HTTP. 

When I load an entry within the CP, I see this error in the console:

```
Mixed Content: The page at 'https://www.domain.com/admin/entries/entry-section/985810-entry-title' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.domaincom/actions/related/default/?id=985810&sectionId=37&userId=&categoryId='. This request has been blocked; the content must be served over HTTPS.
```

The action URL is using HTTP rather than HTTPS. The site is a pretty standard setup – base URL settings in `.env` are using HTTPS, `.htaccess` isn't doing anything with https, there are no plugins like Patrol running, and it's a LetsEncrypt SSL cert.

I can get around this error by setting editing line [28 in Related.js](https://github.com/wrav/related/blob/master/src/assetbundles/related/dist/js/Related.js#L28) to:

```
url: "/admin/actions/related/default?id=" + id + "&sectionId=" + sectionId + "&userId=" + userId + "&categoryId=" + categoryId,
```

Note the addition of '/admin' at the start. This doesn't feel like a proper fix, maybe just a nice coincidence, so I didn't want to open a PR.

I'm wondering if this URL should be set to something else? E.g. currently it also doesn't respect Craft's [actionTrigger](https://craftcms.com/docs/3.x/config/config-settings.html#actiontrigger) setting.

Thanks for any pointers.

**Comment by reganlawton** [comment]
@gavinplatt I'm just about to go into a surgery this morning and gonna be away from computer for a week. So I'm be able to take a look into it when I'm back.

**Comment by reganlawton** [comment]
Updated in latest v2.1.0
