### ISSUE TITLE
Any plans to make this work with Assets too ?

### ISSUE THREAD

**Issue by terryupton** [wrav/related#15]
Would be a amazing if this would work with assets too and show you which pages as asset is used/related to.
Not sure if this is viable, but would be a great addition if it is....

**Comment by aberkie** [comment]
@terryupton I added this in PR #16. It has been merged to `master` but not tagged in a release yet.

**Comment by terryupton** [comment]
Great thanks @aberkie - I will wait for thew release tag to test this out.
Are you planning to release this soon @reganlawton?

**Comment by reganlawton** [comment]
@terryupton thats been released

**Comment by reganlawton** [comment]
also in future to test you can use `dev-master` if waiting on release
