### ISSUE TITLE
getElementTypeById errors

### ISSUE THREAD

**Issue by gixxy22** [wrav/related#17]
I get several of these errors in my log, seems to be related to when entries have assets and the assets are related to the entry.

TypeError: craft\services\Elements::getElementTypeById(): Argument #1 ($elementId) must be of type int, string given, called in /home/tsvg/public_html/nhd/vendor/wrav/related/src/controllers/DefaultController.php on line 68

havent dug deeper as it appears to be working but just seen lots of errors in log related to this plugin.

**Comment by reganlawton** [comment]
This should be resolved
