### ISSUE TITLE
Not working when related field is in a matrix field

### ISSUE THREAD

**Issue by elodiegrondin** [wrav/related#2]
Hello,
First, I'd like to thank you for this plugin which looks great and useful but unfortunately does not work in my case. 
I have a related field inside a matrix. Unfortunately, I always have a "View (0)" link that appears in the sidebar.
Would it be possible to make it work when the related is in a matrix ?
Also I'm on Craft CMS 3.3.20.1.

**Comment by reganlawton** [comment]
I can take a look into that feature. I know the is support for it somewhere I’ll see what I can do.

**Comment by cherrykoda** [comment]
Following - I need this feature in order to consider using the plugin. Thnx!

**Comment by reganlawton** [comment]
@cherrykoda  and @elodiegrondin  This is released in the v1.1.0 release. Please take a look and get back to me if you have issues.
