### ISSUE TITLE
Scope to all sites

### ISSUE THREAD

**Issue by OscarBarrett** [wrav/related#20]
The calls to `find()` in [RelatedService.php](https://github.com/wrav/related/blob/master/src/services/RelatedService.php) don't currently search all sites. So if for example you have a multi-site setup and want to view related elements for a user, some items may not show up.

A quick fix would be to do `find()->site('*')` however there may be cases where you may want to only show related items for the current site, or have a setting to limit which sites are included.

**Comment by reganlawton** [comment]
😅 I never built it with multi site in mind, at that time, I'll have to look into this. Or happy to take a PR or else I might have to look into an optiob for this I think

**Comment by reganlawton** [comment]
Released on v2.1.1
