### ISSUE TITLE
Craft4 - 403 on trying to fetch relations

### ISSUE THREAD

**Issue by Eviltoastey** [wrav/related#23]
Currently all non superAdmin users will not be able to see the relations because the following URL cannot be reached due to missing permissions:

/admin/related/default?id=51814&sectionId=&userId=&categoryId=

if this route is changed to

/actions/related/default?id=51814&sectionId=&userId=&categoryId=

it does work.  Could a change be made to Related.js to use /actions instead of /admin?

Please let me know! Our client really loves this widget and would like to continue using it.

Thanks in advance!

**Comment by reganlawton** [comment]
Check out v2.1.0 @Eviltoastey
