### ISSUE TITLE
Empty Modal appears when creating new entry

### ISSUE THREAD

**Issue by john-henry** [wrav/related#3]
Create a new entry and without saving an empty modal appears on-screen at bottom left

Craft CMS 3.4.5

https://share.getcloudapp.com/E0uq25Yr

**Comment by reganlawton** [comment]
@john-henry Ok this might be an issue with the latest version style changes. I'll look into this.

**Comment by reganlawton** [comment]
@john-henry I can't seem to trigger this BUT I have changes that might resolve the issue in the v1.1.0 release. If you can test and let me know if that resolves it. If it doesnt can I get a list of plugins you have isntalled.

**Comment by john-henry** [comment]
@reganlawton I have a large screen 27" iMac and it appears bottom left. Ill test out new release and report back here thanks

**Comment by reganlawton** [comment]
If you need hit me on discord am in the CraftCMS one and I can work through it with you. That might be why you saw it and not me! I have a laptop but I believe the change I added might resolve it.

**Comment by john-henry** [comment]
I updated but it disappears from sidebar completely now. Whats your discord username?

**Comment by reganlawton** [comment]
reganlawton#1354

**Comment by reganlawton** [comment]
Closing as this fix was released in v1.1.1
