### ISSUE TITLE
Composer deprecation notice

### ISSUE THREAD

**Issue by cap-akimrey** [wrav/related#4]
Deprecation Notice: Class wrav\related\assetbundles\Related\RelatedAsset located in ./vendor/wrav/related/src/assetbundles/related/RelatedAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185

**Comment by reganlawton** [comment]
@cap-akimrey can I get your composer version? I should just have to map the file in the composer.json I'lltry get this out today or over the weekend

**Comment by cap-akimrey** [comment]
It's actually the version of Composer that Fortrabbit is running (I get the notice during deployment build) - Composer v1.10.0. Just came out a couple of days ago, and they added that warning: https://github.com/composer/composer/releases 

Thx!

**Comment by reganlawton** [comment]
@cap-akimrey thanks like I said it should be a simple fix jsut need to find time between projects to sit down and apply and test the change.

**Comment by cap-akimrey** [comment]
For reference, some perspective from the yii folks: [https://github.com/yiisoft/yii2/issues/17918](https://github.com/yiisoft/yii2/issues/17918)

**Comment by reganlawton** [comment]
@cap-akimrey  did you give composer v1.10.1 a shot? Did it fix the error?

**Comment by cap-akimrey** [comment]
@reganlawton Not yet. The composer install is what my host is using, and I haven't done any new code deployments yet. But they have been notified of the need to update. I'll be able to let you know in the next few days.

**Comment by reganlawton** [comment]
I'll keep it open for abit longer but it looks like a composer issues from the links your provided.

**Comment by cap-akimrey** [comment]
My host updated Composer and we get a lot fewer notices, but this still throws a warning:

Deprecation Notice: Class wrav\related\assetbundles\Related\RelatedAsset located in ./vendor/wrav/related/src/assetbundles/related/RelatedAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

Not sure if that’s still a Composer thing or not.

**Comment by reganlawton** [comment]
@cap-akimrey I found the issue on this one see v1.1.3
