### ISSUE TITLE
Empty Modal appears all the time when opening an entry

### ISSUE THREAD

**Issue by cap-akimrey** [wrav/related#5]
The "Related" modal appears always in the lower left corner when opening any entry.
Craft Pro 3.4.9
Related 1.1.1

![Screen Shot 2020-03-20 at 5 27 22 PM](https://user-images.githubusercontent.com/41020122/77210974-5a5ce280-6ad0-11ea-939c-99341c31dec3.png)

**Comment by reganlawton** [comment]
I’ll try look into

**Comment by reganlawton** [comment]
@cap-akimrey Just released v1.1.2
