### ISSUE TITLE
Feature Request: Include users in related data

### ISSUE THREAD

**Issue by terryupton** [wrav/related#6]
It would be great if you could include the ability to see any relationships with users too.
I currently have a field in users that relates to some entries and on those entries it would be great if I could see the related users.

**Comment by reganlawton** [comment]
I jsut need to sit down and assign some time to look into this feature

**Comment by reganlawton** [comment]
@terryupton I've updated the package to support categories and users. The release v1.1.5 should be what you looking for.

**Comment by terryupton** [comment]
Awesome thanks @reganlawton 🎉
